#include <iostream>
#include <vector>
using namespace std;
void printArray(vector<int> arr);
void printArray(vector<vector<int>> arr);

// Q1:
// Leetcode 78: Subsets
// power set -> set of all subsets

void backtrack(vector<int> nums, vector<vector<int>> &result, vector<int> subset, int index);

// TC: O(N.(2^N))
// SC: O(N)
vector<vector<int>> subsets(vector<int> &nums)
{
    // number of subsets = 2^n
    // solve using recursion/backtracking
    // use decision tree

    vector<vector<int>> result;
    vector<int> subset; // current subset

    backtrack(nums, result, subset, 0);

    return result;
}

// i -> index of the value that we are making the decision on
void backtrack(vector<int> nums, vector<vector<int>> &result, vector<int> subset, int index)
{
    // base case: index out of bounds
    if (index >= nums.size())
    {
        result.push_back(subset);
        return;
    }

    // decision to include nums[index]
    subset.push_back(nums[index]);
    backtrack(nums, result, subset, index + 1);

    // decision to exclude nums[index]
    subset.pop_back();
    backtrack(nums, result, subset, index + 1);
}

// same as above question
// Q2: Subsequences of String
/*
You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.
A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.
*/
void backtrack_seq(string str, vector<string> &result, string sequence, int i);

vector<string> subsequences(string str)
{
    vector<string> result;
    string sequence;

    backtrack_seq(str, result, sequence, 0);

    return result;
}

void backtrack_seq(string str, vector<string> &result, string sequence, int i)
{
    if (i >= str.size())
    {
        result.push_back(sequence);
        return;
    }

    // exclude
    backtrack_seq(str, result, sequence, i + 1);

    // include
    sequence.push_back(str[i]);
    backtrack_seq(str, result, sequence, i + 1);
}

int main()
{
    // subsets
    {
        vector<int> nums = {1, 2, 3};
        printArray(nums);
        cout << endl
             << "SUBSETS: " << endl
             << endl;
        printArray(subsets(nums));

        cout << endl;
    }

    // sub sequences
    {
        string str = "abc";
        for (auto s : subsequences(str))
        {
            cout << "\"" << s << "\"" << endl;
        }
    }

    return 0;
}

void printArray(vector<int> arr)
{
    for (int i = 0; i < arr.size(); i++)
        cout << arr[i] << " ";
}

void printArray(vector<vector<int>> arr)
{
    for (int i = 0; i < arr.size(); i++)
    {
        cout << "{ ";
        for (int j = 0; j < arr[i].size(); j++)
            cout << arr[i][j] << " ";
        cout << " }" << endl;
    }
}
